// Code generated by go-swagger; DO NOT EDIT.

// Package restapi File Upload
//
//	Example server uploading a file
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//	  - multipart/form-data
//	  - application/x-www-form-urlencoded
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
