// Code generated by go-swagger; DO NOT EDIT.

package restapi

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Example server uploading a file",
    "title": "File Upload",
    "version": "1.0.0"
  },
  "basePath": "/",
  "paths": {
    "/upload": {
      "post": {
        "consumes": [
          "multipart/form-data"
        ],
        "tags": [
          "uploads"
        ],
        "summary": "uploads",
        "operationId": "uploadFile",
        "parameters": [
          {
            "type": "file",
            "name": "file",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/upload-capped": {
      "post": {
        "consumes": [
          "multipart/form-data"
        ],
        "tags": [
          "uploads"
        ],
        "summary": "uploads",
        "operationId": "uploadCappedFile",
        "parameters": [
          {
            "maxLength": 1024,
            "type": "file",
            "name": "file",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/upload-multiple": {
      "post": {
        "consumes": [
          "multipart/form-data"
        ],
        "tags": [
          "uploads"
        ],
        "summary": "uploads",
        "operationId": "uploadFiles",
        "parameters": [
          {
            "type": "string",
            "name": "desc",
            "in": "formData",
            "required": true
          },
          {
            "maxLength": 1024,
            "type": "file",
            "name": "file1",
            "in": "formData"
          },
          {
            "maxLength": 2048,
            "type": "file",
            "name": "file2",
            "in": "formData"
          },
          {
            "minLength": 512,
            "type": "file",
            "name": "unlimitedFile",
            "in": "formData"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/urlencoded-form": {
      "post": {
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "tags": [
          "uploads"
        ],
        "summary": "uploads",
        "operationId": "uploadURLEncoded",
        "parameters": [
          {
            "type": "string",
            "name": "desc",
            "in": "formData",
            "required": true
          },
          {
            "type": "integer",
            "name": "count",
            "in": "formData",
            "required": true
          },
          {
            "maxLength": 1024,
            "type": "file",
            "name": "file1",
            "in": "formData",
            "required": true
          },
          {
            "maxLength": 2048,
            "type": "file",
            "name": "file2",
            "in": "formData"
          },
          {
            "minLength": 512,
            "type": "file",
            "name": "unlimitedFile",
            "in": "formData"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Example server uploading a file",
    "title": "File Upload",
    "version": "1.0.0"
  },
  "basePath": "/",
  "paths": {
    "/upload": {
      "post": {
        "consumes": [
          "multipart/form-data"
        ],
        "tags": [
          "uploads"
        ],
        "summary": "uploads",
        "operationId": "uploadFile",
        "parameters": [
          {
            "type": "file",
            "name": "file",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/upload-capped": {
      "post": {
        "consumes": [
          "multipart/form-data"
        ],
        "tags": [
          "uploads"
        ],
        "summary": "uploads",
        "operationId": "uploadCappedFile",
        "parameters": [
          {
            "maxLength": 1024,
            "type": "file",
            "name": "file",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/upload-multiple": {
      "post": {
        "consumes": [
          "multipart/form-data"
        ],
        "tags": [
          "uploads"
        ],
        "summary": "uploads",
        "operationId": "uploadFiles",
        "parameters": [
          {
            "type": "string",
            "name": "desc",
            "in": "formData",
            "required": true
          },
          {
            "maxLength": 1024,
            "type": "file",
            "name": "file1",
            "in": "formData"
          },
          {
            "maxLength": 2048,
            "type": "file",
            "name": "file2",
            "in": "formData"
          },
          {
            "minLength": 512,
            "type": "file",
            "name": "unlimitedFile",
            "in": "formData"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/urlencoded-form": {
      "post": {
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "tags": [
          "uploads"
        ],
        "summary": "uploads",
        "operationId": "uploadURLEncoded",
        "parameters": [
          {
            "type": "string",
            "name": "desc",
            "in": "formData",
            "required": true
          },
          {
            "type": "integer",
            "name": "count",
            "in": "formData",
            "required": true
          },
          {
            "maxLength": 1024,
            "type": "file",
            "name": "file1",
            "in": "formData",
            "required": true
          },
          {
            "maxLength": 2048,
            "type": "file",
            "name": "file2",
            "in": "formData"
          },
          {
            "minLength": 512,
            "type": "file",
            "name": "unlimitedFile",
            "in": "formData"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  }
}`))
}
