// Code generated by go-swagger; DO NOT EDIT.

package uploads

import (
	"io"
	"mime/multipart"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// UploadFilesMaxParseMemory sets the maximum size in bytes for
// the multipart form parser for this operation.
//
// The default value is 32 MB.
// The multipart parser stores up to this + 10MB.
var UploadFilesMaxParseMemory int64 = 32 << 20

// UploadFilesMaxBodySize caps the size of the form body.
//
// The default value is 32 MB. Larger bodies will error with http status 413.
var UploadFilesMaxBodySize int64 = 32 << 20

// NewUploadFilesParams creates a new UploadFilesParams object
//
// There are no default values defined in the spec.
func NewUploadFilesParams() UploadFilesParams {

	return UploadFilesParams{}
}

// UploadFilesParams contains all the bound params for the upload files operation
// typically these are obtained from a http.Request
//
// swagger:parameters uploadFiles
type UploadFilesParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: formData
	*/
	Desc string

	/*
	  Max Length: 1024
	  In: formData
	*/
	File1 io.ReadCloser

	/*
	  Max Length: 2048
	  In: formData
	*/
	File2 io.ReadCloser

	/*
	  Min Length: 512
	  In: formData
	*/
	UnlimitedFile io.ReadCloser
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUploadFilesParams() beforehand.
func (o *UploadFilesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r
	isBlocking, err := runtime.BindForm(r,
		runtime.BindFormMaxParseMemory(UploadFilesMaxParseMemory),
		runtime.BindFormMaxBody(UploadFilesMaxBodySize),
		runtime.BindFormFile("file1", false, o.bindFile1),
		runtime.BindFormFile("file2", false, o.bindFile2),
		runtime.BindFormFile("unlimitedFile", false, o.bindUnlimitedFile),
	)
	if err != nil {
		if isBlocking {
			return err
		}

		res = append(res, err)
	}
	fds := runtime.Values(r.Form)

	fdDesc, fdhkDesc, _ := fds.GetOK("desc")
	if err := o.bindDesc(fdDesc, fdhkDesc, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindDesc binds and validates parameter Desc from formData.
func (o *UploadFilesParams) bindDesc(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("desc", "formData", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("desc", "formData", raw); err != nil {
		return err
	}
	o.Desc = raw

	return nil
}

// bindFile1 validates file parameter File1 and assigns it as a *runtime.File on success.
//
// The only supported validations on files are MinLength and MaxLength
func (o *UploadFilesParams) bindFile1(file multipart.File, header *multipart.FileHeader) error {
	size, err := file.Seek(0, io.SeekEnd)
	if err != nil {
		return errors.New(http.StatusInternalServerError, "%s: %v", "file1", err)
	}
	_, err = file.Seek(0, io.SeekStart)
	if err != nil {
		return errors.New(http.StatusInternalServerError, "%s: %v", "file1", err)
	}
	if size > 1024 {
		return errors.ExceedsMaximum("file1", "formData", 1024, false, size)
	}

	o.File1 = &runtime.File{Data: file, Header: header}
	return nil
}

// bindFile2 validates file parameter File1 and assigns it as a *runtime.File on success.
//
// The only supported validations on files are MinLength and MaxLength
func (o *UploadFilesParams) bindFile2(file multipart.File, header *multipart.FileHeader) error {
	size, err := file.Seek(0, io.SeekEnd)
	if err != nil {
		return errors.New(http.StatusInternalServerError, "%s: %v", "file2", err)
	}
	_, err = file.Seek(0, io.SeekStart)
	if err != nil {
		return errors.New(http.StatusInternalServerError, "%s: %v", "file2", err)
	}
	if size > 2048 {
		return errors.ExceedsMaximum("file2", "formData", 2048, false, size)
	}

	o.File2 = &runtime.File{Data: file, Header: header}
	return nil
}

// bindUnlimitedFile validates file parameter File1 and assigns it as a *runtime.File on success.
//
// The only supported validations on files are MinLength and MaxLength
func (o *UploadFilesParams) bindUnlimitedFile(file multipart.File, header *multipart.FileHeader) error {
	size, err := file.Seek(0, io.SeekEnd)
	if err != nil {
		return errors.New(http.StatusInternalServerError, "%s: %v", "unlimitedFile", err)
	}
	_, err = file.Seek(0, io.SeekStart)
	if err != nil {
		return errors.New(http.StatusInternalServerError, "%s: %v", "unlimitedFile", err)
	}
	if size < 512 {
		return errors.ExceedsMinimum("unlimitedFile", "formData", 512, false, size)
	}

	o.UnlimitedFile = &runtime.File{Data: file, Header: header}
	return nil
}
