// Code generated by go-swagger; DO NOT EDIT.

package uploads

import (
	"io"
	"mime/multipart"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UploadURLEncodedMaxParseMemory sets the maximum size in bytes for
// the multipart form parser for this operation.
//
// The default value is 32 MB.
// The multipart parser stores up to this + 10MB.
var UploadURLEncodedMaxParseMemory int64 = 32 << 20

// UploadURLEncodedMaxBodySize caps the size of the form body.
//
// The default value is 32 MB. Larger bodies will error with http status 413.
var UploadURLEncodedMaxBodySize int64 = 32 << 20

// NewUploadURLEncodedParams creates a new UploadURLEncodedParams object
//
// There are no default values defined in the spec.
func NewUploadURLEncodedParams() UploadURLEncodedParams {

	return UploadURLEncodedParams{}
}

// UploadURLEncodedParams contains all the bound params for the upload URL encoded operation
// typically these are obtained from a http.Request
//
// swagger:parameters uploadURLEncoded
type UploadURLEncodedParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: formData
	*/
	Count int64

	/*
	  Required: true
	  In: formData
	*/
	Desc string

	/*
	  Required: true
	  Max Length: 1024
	  In: formData
	*/
	File1 io.ReadCloser

	/*
	  Max Length: 2048
	  In: formData
	*/
	File2 io.ReadCloser

	/*
	  Min Length: 512
	  In: formData
	*/
	UnlimitedFile io.ReadCloser
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUploadURLEncodedParams() beforehand.
func (o *UploadURLEncodedParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r
	isBlocking, err := runtime.BindForm(r,
		runtime.BindFormMaxParseMemory(UploadURLEncodedMaxParseMemory),
		runtime.BindFormMaxBody(UploadURLEncodedMaxBodySize),
		runtime.BindFormFile("file1", true, o.bindFile1),
		runtime.BindFormFile("file2", false, o.bindFile2),
		runtime.BindFormFile("unlimitedFile", false, o.bindUnlimitedFile),
	)
	if err != nil {
		if isBlocking {
			return err
		}

		res = append(res, err)
	}
	fds := runtime.Values(r.Form)

	fdCount, fdhkCount, _ := fds.GetOK("count")
	if err := o.bindCount(fdCount, fdhkCount, route.Formats); err != nil {
		res = append(res, err)
	}
	fdDesc, fdhkDesc, _ := fds.GetOK("desc")
	if err := o.bindDesc(fdDesc, fdhkDesc, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCount binds and validates parameter Count from formData.
func (o *UploadURLEncodedParams) bindCount(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("count", "formData", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("count", "formData", raw); err != nil {
		return err
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("count", "formData", "int64", raw)
	}
	o.Count = value

	return nil
}

// bindDesc binds and validates parameter Desc from formData.
func (o *UploadURLEncodedParams) bindDesc(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("desc", "formData", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("desc", "formData", raw); err != nil {
		return err
	}
	o.Desc = raw

	return nil
}

// bindFile1 validates file parameter File1 and assigns it as a *runtime.File on success.
//
// The only supported validations on files are MinLength and MaxLength
func (o *UploadURLEncodedParams) bindFile1(file multipart.File, header *multipart.FileHeader) error {
	size, err := file.Seek(0, io.SeekEnd)
	if err != nil {
		return errors.New(http.StatusInternalServerError, "%s: %v", "file1", err)
	}
	_, err = file.Seek(0, io.SeekStart)
	if err != nil {
		return errors.New(http.StatusInternalServerError, "%s: %v", "file1", err)
	}
	if size > 1024 {
		return errors.ExceedsMaximum("file1", "formData", 1024, false, size)
	}

	o.File1 = &runtime.File{Data: file, Header: header}
	return nil
}

// bindFile2 validates file parameter File1 and assigns it as a *runtime.File on success.
//
// The only supported validations on files are MinLength and MaxLength
func (o *UploadURLEncodedParams) bindFile2(file multipart.File, header *multipart.FileHeader) error {
	size, err := file.Seek(0, io.SeekEnd)
	if err != nil {
		return errors.New(http.StatusInternalServerError, "%s: %v", "file2", err)
	}
	_, err = file.Seek(0, io.SeekStart)
	if err != nil {
		return errors.New(http.StatusInternalServerError, "%s: %v", "file2", err)
	}
	if size > 2048 {
		return errors.ExceedsMaximum("file2", "formData", 2048, false, size)
	}

	o.File2 = &runtime.File{Data: file, Header: header}
	return nil
}

// bindUnlimitedFile validates file parameter File1 and assigns it as a *runtime.File on success.
//
// The only supported validations on files are MinLength and MaxLength
func (o *UploadURLEncodedParams) bindUnlimitedFile(file multipart.File, header *multipart.FileHeader) error {
	size, err := file.Seek(0, io.SeekEnd)
	if err != nil {
		return errors.New(http.StatusInternalServerError, "%s: %v", "unlimitedFile", err)
	}
	_, err = file.Seek(0, io.SeekStart)
	if err != nil {
		return errors.New(http.StatusInternalServerError, "%s: %v", "unlimitedFile", err)
	}
	if size < 512 {
		return errors.ExceedsMinimum("unlimitedFile", "formData", 512, false, size)
	}

	o.UnlimitedFile = &runtime.File{Data: file, Header: header}
	return nil
}
