// Code generated by go-swagger; DO NOT EDIT.

package uploads

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UploadURLEncodedOKCode is the HTTP code returned for type UploadURLEncodedOK
const UploadURLEncodedOKCode int = 200

/*
UploadURLEncodedOK OK

swagger:response uploadUrlEncodedOK
*/
type UploadURLEncodedOK struct {
}

// NewUploadURLEncodedOK creates UploadURLEncodedOK with default headers values
func NewUploadURLEncodedOK() *UploadURLEncodedOK {

	return &UploadURLEncodedOK{}
}

// WriteResponse to the client
func (o *UploadURLEncodedOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
