// Code generated by go-swagger; DO NOT EDIT.

package uploads

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UploadCappedFileOKCode is the HTTP code returned for type UploadCappedFileOK
const UploadCappedFileOKCode int = 200

/*
UploadCappedFileOK OK

swagger:response uploadCappedFileOK
*/
type UploadCappedFileOK struct {
}

// NewUploadCappedFileOK creates UploadCappedFileOK with default headers values
func NewUploadCappedFileOK() *UploadCappedFileOK {

	return &UploadCappedFileOK{}
}

// WriteResponse to the client
func (o *UploadCappedFileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
