// Code generated by go-swagger; DO NOT EDIT.

package uploads

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UploadCappedFileHandlerFunc turns a function with the right signature into a upload capped file handler
type UploadCappedFileHandlerFunc func(UploadCappedFileParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UploadCappedFileHandlerFunc) Handle(params UploadCappedFileParams) middleware.Responder {
	return fn(params)
}

// UploadCappedFileHandler interface for that can handle valid upload capped file params
type UploadCappedFileHandler interface {
	Handle(UploadCappedFileParams) middleware.Responder
}

// NewUploadCappedFile creates a new http.Handler for the upload capped file operation
func NewUploadCappedFile(ctx *middleware.Context, handler UploadCappedFileHandler) *UploadCappedFile {
	return &UploadCappedFile{Context: ctx, Handler: handler}
}

/*
	UploadCappedFile swagger:route POST /upload-capped uploads uploadCappedFile

uploads
*/
type UploadCappedFile struct {
	Context *middleware.Context
	Handler UploadCappedFileHandler
}

func (o *UploadCappedFile) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUploadCappedFileParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
