// Code generated by go-swagger; DO NOT EDIT.

package uploads

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UploadFilesOKCode is the HTTP code returned for type UploadFilesOK
const UploadFilesOKCode int = 200

/*
UploadFilesOK OK

swagger:response uploadFilesOK
*/
type UploadFilesOK struct {
}

// NewUploadFilesOK creates UploadFilesOK with default headers values
func NewUploadFilesOK() *UploadFilesOK {

	return &UploadFilesOK{}
}

// WriteResponse to the client
func (o *UploadFilesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
