// Code generated by go-swagger; DO NOT EDIT.

package uploads

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UploadURLEncodedHandlerFunc turns a function with the right signature into a upload URL encoded handler
type UploadURLEncodedHandlerFunc func(UploadURLEncodedParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UploadURLEncodedHandlerFunc) Handle(params UploadURLEncodedParams) middleware.Responder {
	return fn(params)
}

// UploadURLEncodedHandler interface for that can handle valid upload URL encoded params
type UploadURLEncodedHandler interface {
	Handle(UploadURLEncodedParams) middleware.Responder
}

// NewUploadURLEncoded creates a new http.Handler for the upload URL encoded operation
func NewUploadURLEncoded(ctx *middleware.Context, handler UploadURLEncodedHandler) *UploadURLEncoded {
	return &UploadURLEncoded{Context: ctx, Handler: handler}
}

/*
	UploadURLEncoded swagger:route POST /urlencoded-form uploads uploadUrlEncoded

uploads
*/
type UploadURLEncoded struct {
	Context *middleware.Context
	Handler UploadURLEncodedHandler
}

func (o *UploadURLEncoded) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUploadURLEncodedParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
