// Code generated by go-swagger; DO NOT EDIT.

package uploads

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UploadFilesHandlerFunc turns a function with the right signature into a upload files handler
type UploadFilesHandlerFunc func(UploadFilesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UploadFilesHandlerFunc) Handle(params UploadFilesParams) middleware.Responder {
	return fn(params)
}

// UploadFilesHandler interface for that can handle valid upload files params
type UploadFilesHandler interface {
	Handle(UploadFilesParams) middleware.Responder
}

// NewUploadFiles creates a new http.Handler for the upload files operation
func NewUploadFiles(ctx *middleware.Context, handler UploadFilesHandler) *UploadFiles {
	return &UploadFiles{Context: ctx, Handler: handler}
}

/*
	UploadFiles swagger:route POST /upload-multiple uploads uploadFiles

uploads
*/
type UploadFiles struct {
	Context *middleware.Context
	Handler UploadFilesHandler
}

func (o *UploadFiles) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUploadFilesParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
