// Code generated by go-swagger; DO NOT EDIT.

package uploads

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UploadURLEncodedReader is a Reader for the UploadURLEncoded structure.
type UploadURLEncodedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UploadURLEncodedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewUploadURLEncodedOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /urlencoded-form] uploadURLEncoded", response, response.Code())
	}
}

// NewUploadURLEncodedOK creates a UploadURLEncodedOK with default headers values
func NewUploadURLEncodedOK() *UploadURLEncodedOK {
	return &UploadURLEncodedOK{}
}

/*
UploadURLEncodedOK describes a response with status code 200, with default header values.

OK
*/
type UploadURLEncodedOK struct {
}

// IsSuccess returns true when this upload Url encoded o k response has a 2xx status code
func (o *UploadURLEncodedOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this upload Url encoded o k response has a 3xx status code
func (o *UploadURLEncodedOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this upload Url encoded o k response has a 4xx status code
func (o *UploadURLEncodedOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this upload Url encoded o k response has a 5xx status code
func (o *UploadURLEncodedOK) IsServerError() bool {
	return false
}

// IsCode returns true when this upload Url encoded o k response a status code equal to that given
func (o *UploadURLEncodedOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the upload Url encoded o k response
func (o *UploadURLEncodedOK) Code() int {
	return 200
}

func (o *UploadURLEncodedOK) Error() string {
	return fmt.Sprintf("[POST /urlencoded-form][%d] uploadUrlEncodedOK", 200)
}

func (o *UploadURLEncodedOK) String() string {
	return fmt.Sprintf("[POST /urlencoded-form][%d] uploadUrlEncodedOK", 200)
}

func (o *UploadURLEncodedOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
