// Code generated by go-swagger; DO NOT EDIT.

package uploads

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewUploadURLEncodedParams creates a new UploadURLEncodedParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUploadURLEncodedParams() *UploadURLEncodedParams {
	return &UploadURLEncodedParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUploadURLEncodedParamsWithTimeout creates a new UploadURLEncodedParams object
// with the ability to set a timeout on a request.
func NewUploadURLEncodedParamsWithTimeout(timeout time.Duration) *UploadURLEncodedParams {
	return &UploadURLEncodedParams{
		timeout: timeout,
	}
}

// NewUploadURLEncodedParamsWithContext creates a new UploadURLEncodedParams object
// with the ability to set a context for a request.
func NewUploadURLEncodedParamsWithContext(ctx context.Context) *UploadURLEncodedParams {
	return &UploadURLEncodedParams{
		Context: ctx,
	}
}

// NewUploadURLEncodedParamsWithHTTPClient creates a new UploadURLEncodedParams object
// with the ability to set a custom HTTPClient for a request.
func NewUploadURLEncodedParamsWithHTTPClient(client *http.Client) *UploadURLEncodedParams {
	return &UploadURLEncodedParams{
		HTTPClient: client,
	}
}

/*
UploadURLEncodedParams contains all the parameters to send to the API endpoint

	for the upload URL encoded operation.

	Typically these are written to a http.Request.
*/
type UploadURLEncodedParams struct {

	// Count.
	Count int64

	// Desc.
	Desc string

	// File1.
	File1 runtime.NamedReadCloser

	// File2.
	File2 runtime.NamedReadCloser

	// UnlimitedFile.
	UnlimitedFile runtime.NamedReadCloser

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the upload URL encoded params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UploadURLEncodedParams) WithDefaults() *UploadURLEncodedParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the upload URL encoded params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UploadURLEncodedParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the upload URL encoded params
func (o *UploadURLEncodedParams) WithTimeout(timeout time.Duration) *UploadURLEncodedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the upload URL encoded params
func (o *UploadURLEncodedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the upload URL encoded params
func (o *UploadURLEncodedParams) WithContext(ctx context.Context) *UploadURLEncodedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the upload URL encoded params
func (o *UploadURLEncodedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the upload URL encoded params
func (o *UploadURLEncodedParams) WithHTTPClient(client *http.Client) *UploadURLEncodedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the upload URL encoded params
func (o *UploadURLEncodedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCount adds the count to the upload URL encoded params
func (o *UploadURLEncodedParams) WithCount(count int64) *UploadURLEncodedParams {
	o.SetCount(count)
	return o
}

// SetCount adds the count to the upload URL encoded params
func (o *UploadURLEncodedParams) SetCount(count int64) {
	o.Count = count
}

// WithDesc adds the desc to the upload URL encoded params
func (o *UploadURLEncodedParams) WithDesc(desc string) *UploadURLEncodedParams {
	o.SetDesc(desc)
	return o
}

// SetDesc adds the desc to the upload URL encoded params
func (o *UploadURLEncodedParams) SetDesc(desc string) {
	o.Desc = desc
}

// WithFile1 adds the file1 to the upload URL encoded params
func (o *UploadURLEncodedParams) WithFile1(file1 runtime.NamedReadCloser) *UploadURLEncodedParams {
	o.SetFile1(file1)
	return o
}

// SetFile1 adds the file1 to the upload URL encoded params
func (o *UploadURLEncodedParams) SetFile1(file1 runtime.NamedReadCloser) {
	o.File1 = file1
}

// WithFile2 adds the file2 to the upload URL encoded params
func (o *UploadURLEncodedParams) WithFile2(file2 runtime.NamedReadCloser) *UploadURLEncodedParams {
	o.SetFile2(file2)
	return o
}

// SetFile2 adds the file2 to the upload URL encoded params
func (o *UploadURLEncodedParams) SetFile2(file2 runtime.NamedReadCloser) {
	o.File2 = file2
}

// WithUnlimitedFile adds the unlimitedFile to the upload URL encoded params
func (o *UploadURLEncodedParams) WithUnlimitedFile(unlimitedFile runtime.NamedReadCloser) *UploadURLEncodedParams {
	o.SetUnlimitedFile(unlimitedFile)
	return o
}

// SetUnlimitedFile adds the unlimitedFile to the upload URL encoded params
func (o *UploadURLEncodedParams) SetUnlimitedFile(unlimitedFile runtime.NamedReadCloser) {
	o.UnlimitedFile = unlimitedFile
}

// WriteToRequest writes these params to a swagger request
func (o *UploadURLEncodedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// form param count
	frCount := o.Count
	fCount := swag.FormatInt64(frCount)
	if fCount != "" {
		if err := r.SetFormParam("count", fCount); err != nil {
			return err
		}
	}

	// form param desc
	frDesc := o.Desc
	fDesc := frDesc
	if fDesc != "" {
		if err := r.SetFormParam("desc", fDesc); err != nil {
			return err
		}
	}
	// form file param file1
	if err := r.SetFileParam("file1", o.File1); err != nil {
		return err
	}

	if o.File2 != nil {

		if o.File2 != nil {
			// form file param file2
			if err := r.SetFileParam("file2", o.File2); err != nil {
				return err
			}
		}
	}

	if o.UnlimitedFile != nil {

		if o.UnlimitedFile != nil {
			// form file param unlimitedFile
			if err := r.SetFileParam("unlimitedFile", o.UnlimitedFile); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
