// Code generated by go-swagger; DO NOT EDIT.

package uploads

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUploadFilesParams creates a new UploadFilesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUploadFilesParams() *UploadFilesParams {
	return &UploadFilesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUploadFilesParamsWithTimeout creates a new UploadFilesParams object
// with the ability to set a timeout on a request.
func NewUploadFilesParamsWithTimeout(timeout time.Duration) *UploadFilesParams {
	return &UploadFilesParams{
		timeout: timeout,
	}
}

// NewUploadFilesParamsWithContext creates a new UploadFilesParams object
// with the ability to set a context for a request.
func NewUploadFilesParamsWithContext(ctx context.Context) *UploadFilesParams {
	return &UploadFilesParams{
		Context: ctx,
	}
}

// NewUploadFilesParamsWithHTTPClient creates a new UploadFilesParams object
// with the ability to set a custom HTTPClient for a request.
func NewUploadFilesParamsWithHTTPClient(client *http.Client) *UploadFilesParams {
	return &UploadFilesParams{
		HTTPClient: client,
	}
}

/*
UploadFilesParams contains all the parameters to send to the API endpoint

	for the upload files operation.

	Typically these are written to a http.Request.
*/
type UploadFilesParams struct {

	// Desc.
	Desc string

	// File1.
	File1 runtime.NamedReadCloser

	// File2.
	File2 runtime.NamedReadCloser

	// UnlimitedFile.
	UnlimitedFile runtime.NamedReadCloser

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the upload files params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UploadFilesParams) WithDefaults() *UploadFilesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the upload files params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UploadFilesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the upload files params
func (o *UploadFilesParams) WithTimeout(timeout time.Duration) *UploadFilesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the upload files params
func (o *UploadFilesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the upload files params
func (o *UploadFilesParams) WithContext(ctx context.Context) *UploadFilesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the upload files params
func (o *UploadFilesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the upload files params
func (o *UploadFilesParams) WithHTTPClient(client *http.Client) *UploadFilesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the upload files params
func (o *UploadFilesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDesc adds the desc to the upload files params
func (o *UploadFilesParams) WithDesc(desc string) *UploadFilesParams {
	o.SetDesc(desc)
	return o
}

// SetDesc adds the desc to the upload files params
func (o *UploadFilesParams) SetDesc(desc string) {
	o.Desc = desc
}

// WithFile1 adds the file1 to the upload files params
func (o *UploadFilesParams) WithFile1(file1 runtime.NamedReadCloser) *UploadFilesParams {
	o.SetFile1(file1)
	return o
}

// SetFile1 adds the file1 to the upload files params
func (o *UploadFilesParams) SetFile1(file1 runtime.NamedReadCloser) {
	o.File1 = file1
}

// WithFile2 adds the file2 to the upload files params
func (o *UploadFilesParams) WithFile2(file2 runtime.NamedReadCloser) *UploadFilesParams {
	o.SetFile2(file2)
	return o
}

// SetFile2 adds the file2 to the upload files params
func (o *UploadFilesParams) SetFile2(file2 runtime.NamedReadCloser) {
	o.File2 = file2
}

// WithUnlimitedFile adds the unlimitedFile to the upload files params
func (o *UploadFilesParams) WithUnlimitedFile(unlimitedFile runtime.NamedReadCloser) *UploadFilesParams {
	o.SetUnlimitedFile(unlimitedFile)
	return o
}

// SetUnlimitedFile adds the unlimitedFile to the upload files params
func (o *UploadFilesParams) SetUnlimitedFile(unlimitedFile runtime.NamedReadCloser) {
	o.UnlimitedFile = unlimitedFile
}

// WriteToRequest writes these params to a swagger request
func (o *UploadFilesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// form param desc
	frDesc := o.Desc
	fDesc := frDesc
	if fDesc != "" {
		if err := r.SetFormParam("desc", fDesc); err != nil {
			return err
		}
	}

	if o.File1 != nil {

		if o.File1 != nil {
			// form file param file1
			if err := r.SetFileParam("file1", o.File1); err != nil {
				return err
			}
		}
	}

	if o.File2 != nil {

		if o.File2 != nil {
			// form file param file2
			if err := r.SetFileParam("file2", o.File2); err != nil {
				return err
			}
		}
	}

	if o.UnlimitedFile != nil {

		if o.UnlimitedFile != nil {
			// form file param unlimitedFile
			if err := r.SetFileParam("unlimitedFile", o.UnlimitedFile); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
