// Code generated by go-swagger; DO NOT EDIT.

package uploads

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUploadCappedFileParams creates a new UploadCappedFileParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUploadCappedFileParams() *UploadCappedFileParams {
	return &UploadCappedFileParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUploadCappedFileParamsWithTimeout creates a new UploadCappedFileParams object
// with the ability to set a timeout on a request.
func NewUploadCappedFileParamsWithTimeout(timeout time.Duration) *UploadCappedFileParams {
	return &UploadCappedFileParams{
		timeout: timeout,
	}
}

// NewUploadCappedFileParamsWithContext creates a new UploadCappedFileParams object
// with the ability to set a context for a request.
func NewUploadCappedFileParamsWithContext(ctx context.Context) *UploadCappedFileParams {
	return &UploadCappedFileParams{
		Context: ctx,
	}
}

// NewUploadCappedFileParamsWithHTTPClient creates a new UploadCappedFileParams object
// with the ability to set a custom HTTPClient for a request.
func NewUploadCappedFileParamsWithHTTPClient(client *http.Client) *UploadCappedFileParams {
	return &UploadCappedFileParams{
		HTTPClient: client,
	}
}

/*
UploadCappedFileParams contains all the parameters to send to the API endpoint

	for the upload capped file operation.

	Typically these are written to a http.Request.
*/
type UploadCappedFileParams struct {

	// File.
	File runtime.NamedReadCloser

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the upload capped file params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UploadCappedFileParams) WithDefaults() *UploadCappedFileParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the upload capped file params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UploadCappedFileParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the upload capped file params
func (o *UploadCappedFileParams) WithTimeout(timeout time.Duration) *UploadCappedFileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the upload capped file params
func (o *UploadCappedFileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the upload capped file params
func (o *UploadCappedFileParams) WithContext(ctx context.Context) *UploadCappedFileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the upload capped file params
func (o *UploadCappedFileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the upload capped file params
func (o *UploadCappedFileParams) WithHTTPClient(client *http.Client) *UploadCappedFileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the upload capped file params
func (o *UploadCappedFileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFile adds the file to the upload capped file params
func (o *UploadCappedFileParams) WithFile(file runtime.NamedReadCloser) *UploadCappedFileParams {
	o.SetFile(file)
	return o
}

// SetFile adds the file to the upload capped file params
func (o *UploadCappedFileParams) SetFile(file runtime.NamedReadCloser) {
	o.File = file
}

// WriteToRequest writes these params to a swagger request
func (o *UploadCappedFileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	// form file param file
	if err := r.SetFileParam("file", o.File); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
