// Code generated by go-swagger; DO NOT EDIT.

package uploads

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UploadCappedFileReader is a Reader for the UploadCappedFile structure.
type UploadCappedFileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UploadCappedFileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewUploadCappedFileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /upload-capped] uploadCappedFile", response, response.Code())
	}
}

// NewUploadCappedFileOK creates a UploadCappedFileOK with default headers values
func NewUploadCappedFileOK() *UploadCappedFileOK {
	return &UploadCappedFileOK{}
}

/*
UploadCappedFileOK describes a response with status code 200, with default header values.

OK
*/
type UploadCappedFileOK struct {
}

// IsSuccess returns true when this upload capped file o k response has a 2xx status code
func (o *UploadCappedFileOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this upload capped file o k response has a 3xx status code
func (o *UploadCappedFileOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this upload capped file o k response has a 4xx status code
func (o *UploadCappedFileOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this upload capped file o k response has a 5xx status code
func (o *UploadCappedFileOK) IsServerError() bool {
	return false
}

// IsCode returns true when this upload capped file o k response a status code equal to that given
func (o *UploadCappedFileOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the upload capped file o k response
func (o *UploadCappedFileOK) Code() int {
	return 200
}

func (o *UploadCappedFileOK) Error() string {
	return fmt.Sprintf("[POST /upload-capped][%d] uploadCappedFileOK", 200)
}

func (o *UploadCappedFileOK) String() string {
	return fmt.Sprintf("[POST /upload-capped][%d] uploadCappedFileOK", 200)
}

func (o *UploadCappedFileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
